
all: p1 p2 p3 p4 1_homework 2_homework 3_homework 4_homework 5_homework 6_homework 7_homework 8_homework

clean:
	rm -f p1 p2 p3 p4 1_homework 2_homework 3_homework 4_homework 5_homework 6_homework 7_homework 8_homework

p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

1_homework: 1_homework.c
	gcc -o 1_homework 1_homework.c -Wall

2_homework: 2_homework.c
	gcc -o 2_homework 2_homework.c -Wall

3_homework: 3_homework.c
	gcc -o 3_homework 3_homework.c -Wall

4_homework: 4_homework.c
	gcc -o 4_homework 4_homework.c -Wall

5_homework: 5_homework.c
	gcc -o 5_homework 5_homework.c -Wall

6_homework: 6_homework.c
	gcc -o 6_homework 6_homework.c -Wall

7_homework: 7_homework.c
	gcc -o 7_homework 7_homework.c -Wall

8_homework: 8_homework.c
	gcc -o 8_homework 8_homework.c -Wall

