all: null malloc array0 array1

clean:
	rm -f null malloc array0 array1

null: null.c
	gcc -g -o null null.c -Wall

malloc: malloc.c
	gcc -g -o malloc malloc.c -Wall

array0: array0.c
	gcc -g -o array0 array0.c -Wall

array1: array1.c
	gcc -g -o array1 array1.c -Wall

